config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    member do #individual
  	  get 'flag'
    end
    collection do #all posts
      get 'archives'
    end
    resources :comments
  end
    
  resources :users, only: [:new, :create]

  get '/register', to: 'users#new'
  post '/validate', to: 'application#validate'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :comments
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :comments
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
	belongs_to :user
	belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@post = Post.find(params[:post_id])
		@comments = Comment.where(post_id: params[:post_id])
		render 'posts/show'
	end
	def show
		@post = Post.find(params[:post_id])
		@comments = Comment.where(post_id: params[:post_id], id: params[:id])
		render 'posts/show'
	end
	def new
		@post = Post.find(params[:post_id])
		@comments = Comment.where(post_id: params[:post_id])
		@new_comment = true
		render 'posts/show'
	end
	def create
		Comment.create(comment: params[:comment], post_id: params[:post_id])
		redirect_to "/posts/#{params[:post_id]}/comments"
	end
	def edit
		@edit_comment = true
		@post = Post.find(params[:post_id])
		@comments = Comment.where(post_id: params[:post_id], id: params[:id])
		render 'posts/show'
	end
	def update
		@comment = Comment.find(params[:id])
		@comment.update_attributes(comment: params[:comment])
		redirect_to "/posts/#{params[:post_id]}/comments"
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  end

  def create
    if params[:title] != nil and params[:title] != "" and params[:url] != nil and params[:url] != ""
  	  Post.create(title: params[:title], description: params[:description], url: params[:url])
    else
      redirect_to '/posts/new', flash[:error] = "Please make sure the new post has a title and url at minimum."
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:title] == nil or params[:title] == "" or params[:url] == nil or params[:url] == ""
      redirect_to "/posts/#{params[:id]}/edit", :flash => {:error => "Please make sure you update the title and url at minimum."}
    else
      @post.update_attributes(title: params[:title])
      if params[:description] != nil and params[:description] != ""
        @post.update_attributes(description: params[:description])
      end
      @post.update_attributes(url: params[:url])
      render :show
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new("#{params[:username]}")
    if @user.save
      redirect_to root_path, notice: 'You are now registered!'
    else
      @user.errors.delete(:password_digest)
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/login.html.erb
<h1>Please login first before proceeding</h1>
<form method="post" action="/validate">
	<h4>Username:</h4><input type="text" name="username">
	<h4>Password:</h4><input type="text" name="password">
	<input type="submit">
</form>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'Create New Post', new_post_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post-it Application</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title Post-it Application
    %meta(name="description" content="")
    %meta(name="author" content="")
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header
      .navbar
        .navbar-inner
          .container
            = render 'layouts/navigation'
    #main(role="main")
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
        %footer
      / ! end of .container
    / ! end of #main

app/views/posts/create.html.erb
<h2>Succesfully posted!</h2>

app/views/posts/edit.html.erb
<h2>Current Post: <%= @post.title %></h2>
<br />
<h5><%= @post.description %></h5>
<p><em><%= @post.url %></em></p>
<br />
<br />
<%= form_for @post, :method => :put do %>
<form method="post" action=<%= "/posts/#{@post.id}" %>>
	Edit Title: <input type="text" name="title">
	Edit description: <input type="text" name="description">
	Edit URL: <input type="text" name="url">
	<br/>
	Submit changes! <input type="submit">
</form>
<% end %>

app/views/posts/index.html.erb
<h2>Welcome to the PostIt!</h2>

<ul>
	<% for i in 0...@posts.count %>
	<li><strong><%= @posts[i].title %></strong></li>
	<li><i><%= @posts[i].description %></i> --- <%= @posts[i].url %></li>
	<br />
	<% end %>
</ul>

app/views/posts/new.html.erb
<h4>Create a new post!</h4>

<form action="/posts" method="post">
	Title: <input name="title" type="text">
	Description: <input name="description" type="text">
	URL: <input name="url" type="text">
	<input type="submit">
</form>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<br />
<h5><%= @post.description %></h5>
<h6><em><%= @post.url %></em></h6>

<br />
<br />

<% if @comments != nil %>
<ul><% @comments.each do |t| %>
  <li><%= t.comment %></li>
    <ul><li>Posted: <%= t.created_at %></li>
    <% if t.user_id != nil %>
	  <li>By: <%= t.user.username %></li></ul>
	  <% end %>
</ul><% end %>
<% end %>

<% if @new_comment == true %>
  <form action=<%="/posts/#{@post.id}/comments"%> method="post">
	  Comment: <input name="comment" type="text">
	  <input type="submit">
  </form>
<% end %>

<% if @edit_comment == true %>
<%= form_for @comments.first, :method => :put, :url => "/posts/#{params[:post_id]}/comments/#{params[:id]}" do %>
	Edit Comment: <input type="text" name="comment">
	<br/>
	Submit changes! <input type="submit">
<% end %>
<% end %>

app/views/users/create.html.erb
<h2>That's a badass new user, son!</h2>

<h4><%=edit_user_url(2)%></h4>

app/views/users/new.html.erb
<h1>Create a new User!</h1>

<form method="post" action="/users">
	Username:
  <input type="text" name="username">
  Password:
  <input type="text" name="password">
  <input type="submit">
</form>